### PR TITLE
Move binaries to libexec

### PR DESCRIPTION
**Pull request by eclipseo**

### CODE REVIEW

**Review by sanjayankur31 — APPROVED** [review]
Looks good.

**Comment by sanjayankur31** [comment]
By the way, PRs can be opened directly on src.fp.o now @fangq since the package has been imported. You needn't keep these spec files here too.

https://src.fedoraproject.org/rpms/octave-iso2mesh

**Comment by sanjayankur31** [comment]
(In fact, I think we should be using src.fp.o only---commits from here cannot be transferred there since the git commit trees are different, right?)

**Comment by fangq** [comment]
@eclipseo, thanks for the patch, will update and rebuild.

@sanjayankur31, I wasn't sure if anyone can fork the spec files in src.fp, so, any user with a fas account can fork? in that case, in the future, I will do the co-dev in src.fp repo directly.

**Comment by sanjayankur31** [comment]
Yes, anyone with an FAS can fork and submit PRs.

**Pull request merged**
